#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Evaluate final cell masks against manual expert cell masks.

This script compares the final area + phasor/GMM filtered cell masks against
manual binary cell masks on a tile-by-tile basis.

The goal is to validate the final segmentation masks used for downstream
immuno-cell analysis.

Input expected per mosaic:
    <mosaic_dir>/<MANUAL_MASK_SUBDIR>/
        manual mask files matching tile numbers

    <mosaic_dir>/<FINAL_MASK_SUBDIR>/
        Im_00001_cell_mask_final.tif
        Im_00002_cell_mask_final.tif
        ...

Outputs:
    <patient_dir>/segmentation_evaluation/final_area_phasor_gmm/
        segmentation_key_metrics_by_tile.csv
        segmentation_metrics_summary.csv
        final_segmentation_key_metrics_panel.png / .pdf
        final_segmentation_object_precision_and_fp_percentage.png / .pdf
        final_segmentation_performance_cards.png / .pdf
        violin_object_precision.png / .pdf
        violin_false_positive_percentage.png / .pdf
        README_segmentation_evaluation.txt

Metrics:
    Pixel-level:
        dice
        iou
        precision

    Object-level:
        object_precision
        fp_objects
        false_positive_percentage
        relative_cell_count_error

How to use:
    1. Edit PATIENT_DIR.
    2. Edit MANUAL_MASK_SUBDIR if needed.
    3. Make sure final masks were generated by build_area_phasor_cell_mask.py.
    4. Run:

        python -m src.segmentation.evaluate_final_masks_against_manual

    or directly:

        python src/segmentation/evaluate_final_masks_against_manual.py
"""

import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tifffile as tiff
from PIL import Image
from skimage.measure import label
from skimage.transform import resize

# =========================
# CONFIG
# =========================

PATIENT_DIR = Path(
    "/Users/schutyb/Documents/balu_lab/dod/data_raw/patients/p449"
).expanduser()

# Temporary/current location.
# Recommended future location: Path("manual_masks")
MANUAL_MASK_SUBDIR = Path("random_forest/mask")

FINAL_MASK_SUBDIR = Path("final_masks_area_phasor_gmm/tiles")

OUTPUT_DIR = PATIENT_DIR / "segmentation_evaluation" / "final_area_phasor_gmm"

MASK_EXTENSIONS = [".png", ".tif", ".tiff"]

METHOD_NAME = "Candidate segmentation + FLIM phasor filtering"

OBJECT_IOU_THRESHOLD = 0.10
FIG_DPI = 600

ALL_METRICS = [
    "dice",
    "iou",
    "precision",
    "object_precision",
    "fp_objects",
    "false_positive_percentage",
    "relative_cell_count_error",
]


# =========================
# STYLE
# =========================


def set_nature_style():
    plt.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 9,
            "axes.titlesize": 10,
            "axes.labelsize": 9,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 8,
            "figure.titlesize": 12,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.linewidth": 0.8,
            "xtick.major.width": 0.8,
            "ytick.major.width": 0.8,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


# =========================
# HELPERS
# =========================


def natural_key(path):
    return [
        int(text) if text.isdigit() else text.lower()
        for text in re.split(r"(\d+)", str(path.name))
    ]


def extract_tile_number(name):
    patterns = [
        r"Im_(\d+)",
        r"_t(\d+)",
        r"tile[_-]?(\d+)",
    ]

    for pattern in patterns:
        match = re.search(pattern, name, re.IGNORECASE)

        if match:
            return int(match.group(1))

    numbers = re.findall(r"\d+", name)

    return int(numbers[-1]) if numbers else None


def read_mask(path):
    if path.suffix.lower() in [".tif", ".tiff"]:
        mask = tiff.imread(path)
    else:
        mask = np.array(Image.open(path))

    if mask.ndim == 3:
        mask = mask[..., 0]

    return mask > 0


def resize_mask_if_needed(mask, target_shape):
    if mask.shape == target_shape:
        return mask

    resized = resize(
        mask.astype(float),
        target_shape,
        order=0,
        preserve_range=True,
        anti_aliasing=False,
    )

    return resized > 0.5


def collect_mask_files(folder):
    if not folder.exists():
        return []

    files = []

    for extension in MASK_EXTENSIONS:
        files.extend(folder.glob(f"*{extension}"))

    return sorted(files, key=natural_key)


def match_by_tile(tile_number, files):
    for path in files:
        if extract_tile_number(path.name) == tile_number:
            return path

    return None


# =========================
# METRICS
# =========================


def pixel_level_metrics(gt, pred):
    gt = gt.astype(bool)
    pred = pred.astype(bool)

    true_positive = np.logical_and(gt, pred).sum()
    false_positive = np.logical_and(~gt, pred).sum()
    false_negative = np.logical_and(gt, ~pred).sum()

    dice_denominator = 2 * true_positive + false_positive + false_negative
    iou_denominator = true_positive + false_positive + false_negative
    precision_denominator = true_positive + false_positive

    dice = (2 * true_positive) / dice_denominator if dice_denominator > 0 else np.nan

    iou = true_positive / iou_denominator if iou_denominator > 0 else np.nan

    precision = (
        true_positive / precision_denominator if precision_denominator > 0 else np.nan
    )

    return {
        "dice": float(dice),
        "iou": float(iou),
        "precision": float(precision),
    }


def object_level_metrics(gt, pred, iou_threshold):
    gt_labels = label(gt, connectivity=2)
    pred_labels = label(pred, connectivity=2)

    gt_ids = np.unique(gt_labels)
    pred_ids = np.unique(pred_labels)

    gt_ids = gt_ids[gt_ids != 0]
    pred_ids = pred_ids[pred_ids != 0]

    n_gt_objects = len(gt_ids)
    n_pred_objects = len(pred_ids)

    matched_gt = set()
    matched_pred = set()

    for pred_id in pred_ids:
        pred_object = pred_labels == pred_id

        best_iou = 0.0
        best_gt_id = None

        overlapping_gt_ids = np.unique(gt_labels[pred_object])
        overlapping_gt_ids = overlapping_gt_ids[overlapping_gt_ids != 0]

        for gt_id in overlapping_gt_ids:
            gt_object = gt_labels == gt_id

            intersection = np.logical_and(pred_object, gt_object).sum()
            union = np.logical_or(pred_object, gt_object).sum()

            iou = intersection / union if union > 0 else 0.0

            if iou > best_iou:
                best_iou = float(iou)
                best_gt_id = int(gt_id)

        if best_iou >= iou_threshold and best_gt_id is not None:
            matched_pred.add(int(pred_id))
            matched_gt.add(best_gt_id)

    tp_objects = len(matched_pred)
    fp_objects = n_pred_objects - tp_objects
    fn_objects = n_gt_objects - len(matched_gt)

    object_precision = (
        tp_objects / (tp_objects + fp_objects)
        if (tp_objects + fp_objects) > 0
        else np.nan
    )

    false_positive_percentage = (
        100.0 * fp_objects / (tp_objects + fp_objects)
        if (tp_objects + fp_objects) > 0
        else np.nan
    )

    cell_count_error = abs(n_pred_objects - n_gt_objects)

    relative_cell_count_error = (
        cell_count_error / n_gt_objects if n_gt_objects > 0 else np.nan
    )

    return {
        "n_gt_objects": int(n_gt_objects),
        "n_pred_objects": int(n_pred_objects),
        "tp_objects": int(tp_objects),
        "fp_objects": int(fp_objects),
        "fn_objects": int(fn_objects),
        "object_precision": float(object_precision),
        "cell_count_error": int(cell_count_error),
        "relative_cell_count_error": float(relative_cell_count_error),
        "false_positive_percentage": float(false_positive_percentage),
    }


def evaluate_single_prediction(gt, pred, meta):
    pred = resize_mask_if_needed(pred, gt.shape)

    pixel_metrics = pixel_level_metrics(gt, pred)
    object_metrics = object_level_metrics(gt, pred, OBJECT_IOU_THRESHOLD)

    return {
        **meta,
        "method": METHOD_NAME,
        "object_iou_threshold": OBJECT_IOU_THRESHOLD,
        **pixel_metrics,
        **object_metrics,
    }


# =========================
# PLOTS
# =========================


def metric_title(metric):
    titles = {
        "precision": "Pixel-level precision",
        "object_precision": "Object-level precision",
        "fp_objects": "False-positive objects / tile",
        "false_positive_percentage": "False-positive objects (%)",
        "relative_cell_count_error": "Relative cell count error",
        "dice": "Dice coefficient",
        "iou": "IoU / Jaccard",
    }

    return titles.get(metric, metric.replace("_", " "))


def metric_ylabel(metric):
    labels = {
        "precision": "Score",
        "object_precision": "Score",
        "false_positive_percentage": "% of predicted objects",
        "fp_objects": "Objects / tile",
        "relative_cell_count_error": "Relative error",
        "dice": "Score",
        "iou": "Score",
    }

    return labels.get(metric, metric_title(metric))


def add_mean_median_lines(axis, values, metric):
    mean_value = np.nanmean(values)
    median_value = np.nanmedian(values)

    if metric == "false_positive_percentage":
        mean_label = f"Mean = {mean_value:.1f}%"
        median_label = f"Median = {median_value:.1f}%"
    else:
        mean_label = f"Mean = {mean_value:.2f}"
        median_label = f"Median = {median_value:.2f}"

    axis.hlines(
        mean_value,
        0.82,
        1.18,
        colors="black",
        linewidth=1.6,
        linestyles="-",
        zorder=4,
        label=mean_label,
    )

    axis.hlines(
        median_value,
        0.82,
        1.18,
        colors="black",
        linewidth=1.4,
        linestyles="--",
        zorder=4,
        label=median_label,
    )


def plot_single_violin(axis, values, metric, seed=0):
    rng = np.random.default_rng(seed)

    violin = axis.violinplot(
        values,
        positions=[1],
        widths=0.65,
        showmeans=False,
        showmedians=False,
        showextrema=False,
    )

    for body in violin["bodies"]:
        body.set_facecolor("#D9D9D9")
        body.set_edgecolor("#6E6E6E")
        body.set_alpha(0.75)
        body.set_linewidth(0.8)

    x_values = 1 + rng.normal(0, 0.035, size=len(values))

    axis.scatter(
        x_values,
        values,
        s=18,
        color="#1F77B4",
        alpha=0.75,
        edgecolors="white",
        linewidths=0.35,
        zorder=3,
    )

    add_mean_median_lines(axis, values, metric)

    axis.set_xticks([1])
    axis.set_xticklabels([METHOD_NAME])
    axis.set_title(metric_title(metric), pad=8)
    axis.set_ylabel(metric_ylabel(metric))
    axis.grid(axis="y", alpha=0.18, linewidth=0.6)

    if metric in ["precision", "object_precision", "dice", "iou"]:
        axis.set_ylim(0, 1.05)

    if metric == "false_positive_percentage":
        axis.set_ylim(0, 100)


def save_violin_plot(df, metric, output_path, ylim=None, seed=0):
    values = df[metric].dropna().astype(float).values

    if len(values) == 0:
        return

    fig, axis = plt.subplots(figsize=(3.2, 4.2), dpi=FIG_DPI)

    plot_single_violin(axis, values, metric, seed=seed)

    if ylim is not None:
        axis.set_ylim(*ylim)

    axis.legend(frameon=False, fontsize=8, loc="best")

    fig.tight_layout()
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def save_two_violin_panel(df, output_path):
    metrics = [
        "object_precision",
        "false_positive_percentage",
    ]

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(6.4, 4.2),
        dpi=FIG_DPI,
    )

    for index, (axis, metric) in enumerate(zip(axes, metrics)):
        values = df[metric].dropna().astype(float).values
        plot_single_violin(axis, values, metric, seed=index)
        axis.legend(frameon=False, fontsize=8, loc="best")

    fig.suptitle(
        "Segmentation performance",
        fontsize=12,
        y=1.02,
    )

    fig.tight_layout()
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def save_key_metrics_panel(df, output_path):
    metrics = [
        "precision",
        "object_precision",
        "false_positive_percentage",
        "relative_cell_count_error",
    ]

    fig, axes = plt.subplots(
        1,
        len(metrics),
        figsize=(12.5, 4.0),
        dpi=FIG_DPI,
    )

    for index, (axis, metric) in enumerate(zip(axes, metrics)):
        values = df[metric].dropna().astype(float).values
        plot_single_violin(axis, values, metric, seed=index)

        if index == 0:
            axis.legend(frameon=False, fontsize=8, loc="best")
        else:
            legend = axis.get_legend()
            if legend is not None:
                legend.remove()

    fig.suptitle(
        "Final segmentation performance against manual annotations",
        fontsize=12,
        y=1.05,
    )

    fig.tight_layout()
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


def save_performance_cards(df, output_path):
    metrics = [
        "precision",
        "object_precision",
        "false_positive_percentage",
        "relative_cell_count_error",
    ]

    fig, axes = plt.subplots(1, len(metrics), figsize=(12.5, 3.2), dpi=FIG_DPI)

    for axis, metric in zip(axes, metrics):
        values = df[metric].dropna().astype(float).values

        mean_value = np.nanmean(values)
        std_value = np.nanstd(values, ddof=1)
        median_value = np.nanmedian(values)
        n_values = len(values)

        axis.axis("off")

        axis.text(
            0.5,
            0.78,
            metric_title(metric),
            ha="center",
            va="center",
            fontsize=9,
            fontweight="bold",
        )

        value_text = f"{mean_value:.2f}"

        if metric == "false_positive_percentage":
            value_text += "%"

        axis.text(
            0.5,
            0.50,
            value_text,
            ha="center",
            va="center",
            fontsize=26,
            fontweight="bold",
        )

        axis.text(
            0.5,
            0.31,
            f"mean ± SD: {mean_value:.2f} ± {std_value:.2f}",
            ha="center",
            va="center",
            fontsize=8,
        )

        axis.text(
            0.5,
            0.20,
            f"median: {median_value:.2f} | n={n_values}",
            ha="center",
            va="center",
            fontsize=8,
        )

        axis.add_patch(
            plt.Rectangle(
                (0.04, 0.08),
                0.92,
                0.82,
                fill=False,
                linewidth=0.8,
                alpha=0.65,
                transform=axis.transAxes,
            )
        )

    fig.suptitle(
        f"Final segmentation performance: {METHOD_NAME}",
        fontsize=12,
    )

    fig.tight_layout()
    fig.savefig(output_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)


# =========================
# README
# =========================


def save_readme(summary_df, output_path):
    lines = []

    lines.append("README - Final segmentation evaluation\n")
    lines.append("=" * 45 + "\n\n")

    lines.append("Method evaluated\n")
    lines.append("----------------\n")
    lines.append(
        f"{METHOD_NAME}: candidate segmentation masks followed by area filtering "
        "and ROI-level FLIM phasor/GMM filtering.\n\n"
    )

    lines.append("Ground truth\n")
    lines.append("------------\n")
    lines.append(
        "Manual binary masks containing only immune cells were used as ground truth.\n\n"
    )

    lines.append("Object matching\n")
    lines.append("---------------\n")
    lines.append(
        f"A predicted object is considered a true-positive object when its best "
        f"IoU overlap with a manual object is >= {OBJECT_IOU_THRESHOLD}.\n\n"
    )

    lines.append("Files generated\n")
    lines.append("---------------\n")
    lines.append("segmentation_key_metrics_by_tile.csv\n")
    lines.append("segmentation_metrics_summary.csv\n")
    lines.append("final_segmentation_key_metrics_panel.png / .pdf\n")
    lines.append("final_segmentation_object_precision_and_fp_percentage.png / .pdf\n")
    lines.append("final_segmentation_performance_cards.png / .pdf\n")
    lines.append("violin_object_precision.png / .pdf\n")
    lines.append("violin_false_positive_percentage.png / .pdf\n\n")

    lines.append("Summary values\n")
    lines.append("--------------\n")

    for _, row in summary_df.iterrows():
        lines.append(
            f"{row['metric_label']}: "
            f"mean={row['mean']:.4f}, "
            f"std={row['std']:.4f}, "
            f"median={row['median']:.4f}, "
            f"n={int(row['count'])}\n"
        )

    output_path.write_text("".join(lines))


# =========================
# MAIN
# =========================


def main():
    set_nature_style()

    if not PATIENT_DIR.exists():
        raise FileNotFoundError(f"No existe PATIENT_DIR:\n{PATIENT_DIR}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    rows = []

    visit_dirs = sorted(
        [path for path in PATIENT_DIR.glob("visit*") if path.is_dir()],
        key=natural_key,
    )

    if len(visit_dirs) == 0:
        print("[WARN] No se encontraron carpetas visit*.")
        return

    for visit_dir in visit_dirs:
        visit_name = visit_dir.name

        mosaic_dirs = sorted(
            [path for path in visit_dir.glob("Mosaic*") if path.is_dir()],
            key=natural_key,
        )

        for mosaic_dir in mosaic_dirs:
            mosaic_name = mosaic_dir.name

            manual_dir = mosaic_dir / MANUAL_MASK_SUBDIR
            final_dir = mosaic_dir / FINAL_MASK_SUBDIR

            manual_files = collect_mask_files(manual_dir)

            if len(manual_files) == 0:
                continue

            final_files = collect_mask_files(final_dir)

            print(f"\n[PROCESS] {visit_name} | {mosaic_name}")
            print(f"Manual masks: {len(manual_files)}")
            print(f"Final masks:  {len(final_files)}")

            for manual_file in manual_files:
                tile_number = extract_tile_number(manual_file.name)

                if tile_number is None:
                    print(f"[WARN] Could not extract tile number: {manual_file}")
                    continue

                final_file = match_by_tile(tile_number, final_files)

                if final_file is None:
                    print(f"[WARN] Missing final mask for tile {tile_number}")
                    continue

                gt = read_mask(manual_file)
                pred = read_mask(final_file)

                meta = {
                    "visit": visit_name,
                    "mosaic": mosaic_name,
                    "tile": tile_number,
                    "manual_mask": str(manual_file),
                    "final_mask": str(final_file),
                }

                row = evaluate_single_prediction(gt, pred, meta)
                rows.append(row)

    if len(rows) == 0:
        print("\nNo evaluation rows generated.")
        return

    df = pd.DataFrame(rows)

    keep_cols = [
        "visit",
        "mosaic",
        "tile",
        "method",
        "object_iou_threshold",
        "manual_mask",
        "final_mask",
        "dice",
        "iou",
        "precision",
        "object_precision",
        "fp_objects",
        "false_positive_percentage",
        "relative_cell_count_error",
        "n_gt_objects",
        "n_pred_objects",
        "tp_objects",
        "fp_objects",
        "fn_objects",
        "cell_count_error",
    ]

    keep_cols = [column for column in keep_cols if column in df.columns]
    df = df[keep_cols]

    summary = (
        df[ALL_METRICS]
        .agg(["mean", "std", "median", "count"])
        .T.reset_index()
        .rename(columns={"index": "metric"})
    )

    summary["metric_label"] = summary["metric"].map(metric_title)

    tile_csv = OUTPUT_DIR / "segmentation_key_metrics_by_tile.csv"
    summary_csv = OUTPUT_DIR / "segmentation_metrics_summary.csv"

    df.to_csv(tile_csv, index=False)
    summary.to_csv(summary_csv, index=False)

    save_key_metrics_panel(
        df,
        OUTPUT_DIR / "final_segmentation_key_metrics_panel.png",
    )

    save_two_violin_panel(
        df,
        OUTPUT_DIR / "final_segmentation_object_precision_and_fp_percentage.png",
    )

    save_performance_cards(
        df,
        OUTPUT_DIR / "final_segmentation_performance_cards.png",
    )

    save_violin_plot(
        df,
        "object_precision",
        OUTPUT_DIR / "violin_object_precision.png",
        ylim=(0, 1.05),
    )

    save_violin_plot(
        df,
        "false_positive_percentage",
        OUTPUT_DIR / "violin_false_positive_percentage.png",
        ylim=(0, 100),
    )

    save_readme(
        summary,
        OUTPUT_DIR / "README_segmentation_evaluation.txt",
    )

    print("\n[DONE]")
    print(f"Tile metrics:\n{tile_csv}")
    print(f"Summary:\n{summary_csv}")
    print(f"Plots and README saved in:\n{OUTPUT_DIR}")


if __name__ == "__main__":
    main()
