#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Create a high-resolution multi-page PDF with all RGB mosaics from one patient.

This script assumes that src/utils/flim2rgb.py was already run and that each
mosaic folder contains an RGB output folder like:

    patient_folder/
        visit01/
            Mosaic01/
                RGB/
                    Mosaic01.png

Output:
    patient_folder/<patient_id>_RGB_mosaics_QC.pdf
"""

import re
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from PIL import Image


# =========================
# CONFIG
# =========================

PATIENT_FOLDER = Path(
    "/Users/schutyb/Documents/balu_lab/dod/data_raw/patients/p427"
).expanduser()

OUTPUT_PDF = None
# If None, output will be:
# PATIENT_FOLDER / f"{PATIENT_FOLDER.name}_RGB_mosaics_QC.pdf"

RGB_OUTPUT_SUBDIR = "RGB"

PDF_DPI = 600

TITLE_FONTSIZE = 10
TITLE_PAD_INCH = 0.35

OVERWRITE = True


# =========================
# HELPERS
# =========================


def natural_key(path):
    """
    Natural sorting key for paths containing numbers.

    Example:
        visit2 comes before visit10.
        Mosaic2 comes before Mosaic10.
    """
    return [
        int(t) if t.isdigit() else t.lower()
        for t in re.split(r"(\d+)", str(path.name))
    ]


def find_visit_dirs(patient_dir):
    """
    Find visit directories inside the patient folder.
    """
    visit_dirs = [
        path
        for path in patient_dir.iterdir()
        if path.is_dir() and path.name.lower().startswith("visit")
    ]

    return sorted(visit_dirs, key=natural_key)


def find_mosaic_dirs(visit_dir):
    """
    Find mosaic directories inside one visit folder.
    """
    mosaic_dirs = [
        path
        for path in visit_dir.iterdir()
        if path.is_dir() and path.name.lower().startswith("mosaic")
    ]

    return sorted(mosaic_dirs, key=natural_key)


def find_rgb_mosaic_png(mosaic_dir):
    """
    Find the RGB mosaic PNG generated by flim2rgb.py inside:

        mosaic_dir / RGB / *_RGB_mosaic.png

    Returns:
        Path or None.
    """
    rgb_dir = mosaic_dir / RGB_OUTPUT_SUBDIR

    if not rgb_dir.exists():
        return None

    candidates = sorted(
        rgb_dir.glob("*_RGB_mosaic.png"),
        key=natural_key,
    )

    if len(candidates) == 0:
        return None

    if len(candidates) > 1:
        print(f"  [WARN] Más de un RGB mosaic encontrado en: {rgb_dir}")
        print("         Usando el primero:")
        print(f"         {candidates[0]}")

    return candidates[0]


def collect_rgb_mosaics(patient_dir):
    """
    Collect all RGB mosaic PNGs from all visits and mosaics.

    Returns:
        list of dictionaries:
            {
                "visit_name": str,
                "mosaic_name": str,
                "image_path": Path,
            }
    """
    records = []

    visit_dirs = find_visit_dirs(patient_dir)

    for visit_dir in visit_dirs:
        mosaic_dirs = find_mosaic_dirs(visit_dir)

        for mosaic_dir in mosaic_dirs:
            image_path = find_rgb_mosaic_png(mosaic_dir)

            if image_path is None:
                print(
                    f"  [SKIP] No RGB mosaic found for: "
                    f"{visit_dir.name}/{mosaic_dir.name}"
                )
                continue

            records.append(
                {
                    "visit_name": visit_dir.name,
                    "mosaic_name": mosaic_dir.name,
                    "image_path": image_path,
                }
            )

    return records


def add_image_page_to_pdf(pdf, image_path, title, dpi=PDF_DPI):
    """
    Add one RGB mosaic image as one page in the PDF.

    The figure size is derived from the image pixel size and target DPI.
    This keeps the raster image embedded at high resolution.
    """
    with Image.open(image_path) as img:
        img = img.convert("RGB")
        width_px, height_px = img.size

        width_in = width_px / dpi
        height_in = height_px / dpi

        fig_width = width_in
        fig_height = height_in + TITLE_PAD_INCH

        fig = plt.figure(figsize=(fig_width, fig_height), dpi=dpi)

        ax = fig.add_axes(
            [
                0.0,
                0.0,
                1.0,
                height_in / fig_height,
            ]
        )

        ax.imshow(img)
        ax.axis("off")

        fig.suptitle(
            title,
            fontsize=TITLE_FONTSIZE,
            y=0.985,
        )

        pdf.savefig(fig, dpi=dpi)
        plt.close(fig)


def make_pdf(patient_dir, output_pdf, dpi=PDF_DPI):
    """
    Create the final multipage PDF.
    """
    records = collect_rgb_mosaics(patient_dir)

    if len(records) == 0:
        print("\n[WARN] No se encontraron mosaicos RGB.")
        print("       Asegurate de haber corrido primero flim2rgb.py.")
        return

    output_pdf.parent.mkdir(parents=True, exist_ok=True)

    if output_pdf.exists() and not OVERWRITE:
        raise FileExistsError(f"El PDF ya existe:\n{output_pdf}")

    print("\n==============================")
    print("Creando PDF RGB mosaics")
    print("==============================")
    print(f"Paciente: {patient_dir}")
    print(f"Output:   {output_pdf}")
    print(f"DPI:      {dpi}")
    print(f"Páginas:  {len(records)}")

    with PdfPages(output_pdf) as pdf:
        for idx, record in enumerate(records, start=1):
            visit_name = record["visit_name"]
            mosaic_name = record["mosaic_name"]
            image_path = record["image_path"]

            title = f"{visit_name} - {mosaic_name}"

            print(f"[{idx}/{len(records)}] {title}")
            print(f"    {image_path}")

            add_image_page_to_pdf(
                pdf=pdf,
                image_path=image_path,
                title=title,
                dpi=dpi,
            )

    print("\nListo.")
    print(f"PDF guardado en:\n{output_pdf}")


# =========================
# MAIN
# =========================


def main():
    """
    Create RGB mosaic QC PDF for the configured patient folder.
    """
    patient_dir = PATIENT_FOLDER.resolve()

    if not patient_dir.exists():
        raise FileNotFoundError(f"No existe PATIENT_FOLDER:\n{patient_dir}")

    if OUTPUT_PDF is None:
        output_pdf = patient_dir / f"{patient_dir.name}_RGB_mosaics_QC.pdf"
    else:
        output_pdf = Path(OUTPUT_PDF).expanduser().resolve()

    make_pdf(
        patient_dir=patient_dir,
        output_pdf=output_pdf,
        dpi=PDF_DPI,
    )


if __name__ == "__main__":
    main()